name: Maven Build

on: push


jobs:
  Buildartifact:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
        
    steps:
      - name: Clone the code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven 3.8.4
        uses: stCarolas/setup-maven@v4.5
        with: 
          maven-version: '3.8.4'

      - name: Clean Maven build
        run: mvn clean

      - name: Code testing
        run: mvn test

      - name: Build artifact
        run: |
          mvn install
          mkdir staging && cp target/*.jar staging
          ls staging

  # Rest of the jobs remain unchanged...
